server:
  address: 0.0.0.0
  port: 8171
  servlet:
    context-path: /api/judge
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /api
spring:
  application:
    name: online-judge-backend-judge-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Wws970624,.
    username: wuwangsheng
    url: jdbc:mysql://43.138.248.167:3306/oj?useSSL=false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: 127.0.0.1
    database: 2
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: guest
    username: guest
# mybatis-plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# todo 阿里云对象存储
aliyun:
  oss:
    file:
      endpoint: xxxxx
      keyid: xxxx
      keysecret: xxxxx
      bucketname: xxxxxx
knife4j:
  enable: true
# 代码沙箱配置
codesandbox:
  type: remote